GROQ_API_KEY = "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"
COMPANY_DATA_PATH = "./data/compny.docx"
COMPNY_JSON="./data/company_data.json"
GEMINI_API_KEY="AIzaSyBuuJvcXGFPltCUQqwNW6yO-lr4PtHGWQ0"
OUTPUT_FILE = "./data/submission_checklist.json"